# Write your MySQL query statement below
SELECT CUSTOMER_ID 
FROM CUSTOMER 
GROUP BY CUSTOMER_ID 
HAVING COUNT(DISTINCT(PRODUCT_KEY)) = ( SELECT COUNT(*) FROM PRODUCT );

--  USING CTE 
-- WITH TOTAL_PRODUCTS AS (
--     SELECT COUNT(*) AS TOTAL FROM PRODUCT
-- ),
-- COUNT_CUSTOMERS AS ( 
--     SELECT CUSTOMER_ID, COUNT(DISTINCT(PRODUCT_KEY)) AS TOTAL_COUNT 
--     FROM CUSTOMER 
--     GROUP BY CUSTOMER_ID
-- )
-- SELECT C.CUSTOMER_ID 
-- FROM COUNT_CUSTOMERS C JOIN TOTAL_PRODUCTS T ON C.TOTAL_COUNT = T.TOTAL ;