# Write your MySQL query statement below
-- SELECT ACTIVITY_DATE AS DAY ,COUNT(DISTINCT USER_ID) AS ACTIVE_USER
-- FROM ACTIVITY 
-- WHERE ACTIVITY_DATE BETWEEN '2019-06-28' AND '2019-07-27'
-- GROUP BY DAY 
-- THIS CODE ALSO SHOWS THE SAME ANSWER 


WITH DAILY_COUNTS AS (
    SELECT ACTIVITY_DATE AS DAY , COUNT(DISTINCT(USER_ID)) AS ACTIVE_USERS
    FROM ACTIVITY 
    WHERE ACTIVITY_DATE BETWEEN '2019-06-28' AND '2019-07-27'
    GROUP BY ACTIVITY_DATE 
 ) 
 SELECT DAY , ACTIVE_USERS
 FROM DAILY_COUNTS
ORDER BY DAY;
