# Write your MySQL query statement below
WITH MAX_NUMBER AS (SELECT NUM 
FROM MYNUMBERS
GROUP BY NUM
HAVING COUNT(*) = 1 
) 
SELECT MAX(NUM) AS NUM
FROM MAX_NUMBER ;

-- SELECT MAX(NUM) AS NUM
-- FROM MYNUMBERS
-- GROUP BY NUM
-- HAVING COUNT(*) = 1
-- ORDER BY NUM DESC
-- LIMIT 1;

--  USING SUBQUERIES
-- SELECT MAX(NUM) AS NUM
-- FROM (
--   SELECT NUM
--   FROM MYNUMBERS
--   GROUP BY NUM
--   HAVING COUNT(*) = 1
-- ) ;

