# Write your MySQL query statement below
SELECT E.EMPLOYEE_ID AS employee_id
 , E.NAME as name 
 , COUNT(R.REPORTS_TO) AS reports_count 
 , ROUND(AVG(R.AGE )) AS average_age
FROM EMPLOYEES E JOIN EMPLOYEES R ON E.EMPLOYEE_ID = R.REPORTS_TO 
GROUP BY E.EMPLOYEE_ID , E.NAME
ORDER BY E.EMPLOYEE_ID;



--  using cte 
-- WITH DIRECTREPORT AS (
--     SELECT REPORTS_TO AS MANAGER_ID 
--     , COUNT(*) AS REPORTS_COUNT
--     ,ROUND(AVG(AGE)) AS AVERAGE_AGE 
--     FROM EMPLOYEES 
--     WHERE REPORTS_TO IS NOT NULL
--     GROUP BY REPORTS_TO
-- )
-- SELECT E.EMPLOYEE_ID , E.NAME , D.REPORTS_COUNT , D.AVERAGE_AGE
-- FROM EMPLOYEES E
-- JOIN 
-- DIRECTREPORT D ON
-- E.EMPLOYEE_ID = D.MANAGER_ID 
-- ORDER BY E.EMPLOYEE_ID ;