# Write your MySQL query statement below
SELECT USER_ID,
  CONCAT(UPPER(LEFT(name, 1)), LOWER(RIGHT(name, LENGTH(name) - 1))) AS NAME
FROM USERS
ORDER BY USER_ID ;

-- USING SUBSTRING
-- SELECT USER_ID,
--   CONCAT(UPPER(SUBSTRING(NAME, 1, 1)), LOWER(SUBSTRING(NAME, 2))) AS NAME
-- FROM USERS
-- ORDER BY USER_ID ;
