# Write your MySQL query statement below
WITH COUNT_OF_STUDENTS AS (
    SELECT CLASS, COUNT(STUDENT) AS STUDENT_COUNT
    FROM COURSES
    GROUP BY CLASS
) 
SELECT CLASS
FROM COUNT_OF_STUDENTS
WHERE STUDENT_COUNT >= 5;


-- WITH OUT USE OF CTE 
-- SELECT CLASS 
-- FROM COURSES
-- GROUP BY CLASS 
-- HAVING COUNT(STUDENT) >= 5;